services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - app_network

  app:
    build: .
    env_file: '.env'
    environment:
      DATABASE_HOST: db
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
