# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
from typing import Any


@dataclasses.dataclass()
class User:
    id: Any
    first_name: Any
    last_name: Any
